##########################################################
# Filename: cfn-main.yaml

# Version History : v1: #  Authored by Roberto to deploy a SageMaker notebook
############################################################
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ClientName:
    Type: String
    Description: REQUIRED - Name of the Client. Abbreviated client name (e.g. aabg) in lower case letters - this must be all one word alphanumeric
    MinLength: 1
    MaxLength: 20
    AllowedPattern: ^[a-zA-Z0-9]*$
    ConstraintDescription: must only contain letters (uppercase and lowercase) and numbers
  ProductName:
    Type: String
    Description: REQUIRED - Name of the Product (e.g. artifact) in lower case letters - this must be all one word alphanumeric
    MinLength: 1
    MaxLength: 10
    AllowedPattern: ^[a-zA-Z0-9]*$
    ConstraintDescription: must only contain letters (uppercase and lowercase) and numbers
  ModuleName:
    Type: String
    Description: REQUIRED - Please enter the name of the module in lower case letters (e.g. byom)
  ModuleVersion:
    Type: String
    Description: REQUIRED - Version of the module in lower case letters (e.g. v1)
  InstanceType:
    Type: String
    Description: REQUIRED - The type of ML compute instance to launch for the notebook instance
  NotebookInstanceName:
    Type: String
    Description: REQUIRED - The name of the new notebook instance.
  VolumeSizeInGB:
    Type: String
    Description: The size, in GB, of the ML storage volume to attach to the notebook instance
    Default: 5
  SubnetId:
    Type: String
    Description: The ID of the subnet in a VPC to which you would like to have a connectivity from your ML compute instance.
    Default: ""
  SecurityGroupIds:
    Type: List<String>
    Description: The VPC security group IDs, in the form sg-xxxxxxxx. The security groups must be for the same VPC as specified in the subnet.
    Default: ""

Conditions:
  IsSubnetIdEmpty: !Not [ !Equals [!Ref SubnetId, ""] ]
  IsSecurityGroupIdsEmpty: !Not [ !Equals [ !Join ["",!Ref SecurityGroupIds], ""] ]

Resources:
  SageMakerNotebook: # Creates a SageMaker Notebook Instance
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref InstanceType
      NotebookInstanceName:
          !Sub '${ClientName}-${ProductName}-${AWS::Region}-${ModuleName}-${ModuleVersion}-${NotebookInstanceName}'  
      RoleArn:
        Fn::GetAtt:
        - SageMakerExecutionRole
        - Arn
      Tags:
        - Key:   Module
          Value: !Ref ModuleName
        - Key:   Project
          Value: !Ref ClientName
        - Key:   ModuleVersion
          Value: !Ref ModuleVersion
        - Key:   Product
          Value: !Ref ProductName
      VolumeSizeInGB: !Ref VolumeSizeInGB
      AdditionalCodeRepositories:
        - "https://github.com/vbala81/order-accuracy"
      SubnetId: !If [ IsSubnetIdEmpty, !Ref SubnetId, !Ref "AWS::NoValue" ]
      SecurityGroupIds: !If [ IsSecurityGroupIdsEmpty, !Ref SecurityGroupIds, !Ref "AWS::NoValue" ]
  NotebookAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:*
              - iam:PassRole
              - logs:*
              - sagemaker:*
            Effect: Allow
            Resource: "*"
          - Action: s3:ListAllMyBuckets
            Effect: Allow
            Resource: arn:aws:s3:::*
          - Action: s3:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: 
        !Sub '${ClientName}-${ProductName}-${AWS::Region}-${ModuleName}-${ModuleVersion}-${NotebookInstanceName}-policy'      
      Roles:
        - Ref: SageMakerExecutionRole      
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClientName}-${ProductName}-${AWS::Region}-${ModuleName}-${ModuleVersion}-${NotebookInstanceName}-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerFullAccess"
Outputs: # Instance Id
   BasicNotebookInstanceId:
    Value: !Ref SageMakerNotebook

