/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-1",
//     "aws_appsync_graphqlEndpoint": "https://xj6uynoq2ffh5o3z5csiy45cy4.appsync-api.us-east-1.amazonaws.com/graphql",
//     "aws_appsync_region": "us-east-1",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-xbpkasqkznev5fau7eqavtnn7q"
// };

const awsmobile = {
    "aws_api_gateway_url" : "https://rurxs9jlzb.execute-api.us-east-1.amazonaws.com/develop",
    "web_socket_url" : "wss://iaj0nraqpd.execute-api.us-east-1.amazonaws.com/develop"
}


export default awsmobile;
